### PR TITLE
Update tests (partly).

### PR DESCRIPTION
**Pull request by mkcor**
Hi @mplewis !

I'm interested in contributing to this project so I can use input files with other delimiters (`;` or tabs).  I would add an optional argument such as `-d, --delimiter`, where `,` is the default.

To do things well, I started by setting up the testing environment.  I'm not sure where you're at wrt the testing structure.  It wasn't smooth but I was able to get somewhere.

First, I had to upgrade `sure` not to run into https://github.com/gabrielfalcao/sure/issues/80 (hence commit b08e016).

Then, running `test_all_csv_files()`, I would get an `AssertionError` from the EOLs.  Reading a plain `\n` as in this [output file](https://github.com/mplewis/csvtomd/blob/264ee48c1fe05ef2198697e88f34bae581654caa/test/output/normal.md) leads to a `\\n` because the `\` is escaped...  I made the newlines manually (deb5bcc) and then the test would pass.  Note that I didn't fix the second input-output pair (`jagged`) so I checked my piece of improvement by adding a `break` statement at the [end of the block](https://github.com/mplewis/csvtomd/blob/264ee48c1fe05ef2198697e88f34bae581654caa/test/test_csvtomd.py#L17).

Thanks for your consideration.

### CODE REVIEW

**Comment by mplewis** [comment]
Hey @mkcor, thanks for taking a look!

I updated my tests a bit to try and make this project testable. Some of the changes I made look like the ones you did. Want to check out what is available on master?

**Comment by mplewis** [comment]
Hey @mkcor, thanks for taking a look!

I updated my tests a bit to try and make this project testable. Some of the changes I made look like the ones you did. Want to check out what is available on master?

**Comment by mplewis** [comment]
Hi @mkcor. Thanks for your help – sorry it took me so long to get back to you.

csvtomd has proper delimiter support now, including automated tests. Check it out! 🍾

**Comment by mkcor** [comment]
I will!  Thanks, @mplewis .

**Pull request closed without merging**
